
GET http://localhost:5000 


###



POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "nii@linked.com",
  "password": "1235+"
 
}




###



POST   http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "fullname": "nini chouchen",
  "email": "nini@linked.com",
  "password": "55448554+"
 
}
###


POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "nini@linked.com",
  "password": "55448554+"
 
}
###


POST   http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "fullname": "wassim chouchen",
  "email": "nizarrr@linked.com",

  "password": "12349"
}
