
GET http://localhost:5000 


###



POST http://localhost:5000/api/job_card
Content-Type: application/json

{
  "company": "Joi.string().required()",
  "location": "Joi.string().required()",
  "date": "Joi.string()",
  "tasks": "Joi.string().required()",
  "about": "Joi.string().required()",
  "requirements": "Joi.string().required()",
  "applied": "Joi.number().required()",
  "type": "Joi.string().required()",
  "aboutCompany": "Joi.string().required()"
}

###



POST   http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "fullname": "siwar chouchen",
  "email": "wassim@linked.com",
  "password": "12345678+"
 
}
###



POST   http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "fullname": "wassim chouchen",
  "email": "nizarrr@linked.com",

  "password": "12349"
}
